sudo: required
dist: trusty
language: minimal

before_install:
  - "wget 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.7.0/alpine-chroot-install' \
        && echo '090d323d887ef3a2fd4e752428553f22a52b87bb  alpine-chroot-install' | sha1sum -c || exit 1"
  - alpine() { /alpine/enter-chroot -u "$USER" "$@"; }
install:
  - sudo sh alpine-chroot-install -b edge
        -p 'build-base linux-headers util-linux-dev kmod-dev cryptsetup-dev sudo'
        -p 'cryptsetup e2fsprogs'
before_script:
  - /alpine/enter-chroot addgroup $USER wheel
script:
  - alpine ./test.sh -x -y
  - alpine ./test.sh -x -y header

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#alpine-commits"
    template:
      - "%{repository_name}:%{branch} [%{result}] |%{author}| %{commit_subject} | %{build_url}"
