#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

title 'Installing dependencies'

# Build dependencies
alpine_run <<-EOF
	apk add linux-headers util-linux-dev kmod-dev cryptsetup-dev
EOF

# Runtime dependencies
alpine_run <<-EOF
	apk add cryptsetup e2fsprogs
EOF
