#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

title 'Setting up Alpine Linux'

mkdir -p "${ALPINE_ROOT}${CLONE_DIR}"
mount --bind "$CLONE_DIR" "${ALPINE_ROOT}${CLONE_DIR}"

alpine_run <<-EOF
	apk add alpine-sdk

	adduser -G users -s /bin/sh -D $ALPINE_USER
	addgroup $ALPINE_USER abuild
	addgroup $ALPINE_USER wheel

	echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel
EOF
